services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/auth
    container_name: auth
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: gateway
    container_name: gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - rabbitmq
    environment:
      - AUTH_SERVICE_URL=http://auth:3001
